[alias] 
build-firmware = "build --package firmware --target riscv32imac-unknown-none-elf"
run-firmware = "run --package firmware --target riscv32imac-unknown-none-elf"
check-firmware = "check --package firmware --target riscv32imac-unknown-none-elf"
build-server = "build --package server"
run-server = "run --package server"
check-server = "check --package server"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[env]
ESP_LOG="info"
MCU="esp32c6"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["alloc", "core"]
